x = input('Digite algo:')
print('O tipo primitivo deste valor é:',type(x))
print('Apenas espaço:',x.isspace())
print('É um número.',x.isnumeric())
print('É alfabetico.',x.isalpha())
print('É alfanumerico.',x.isalnum())
print('É maiúscula.',x.isupper())
print('É minúscula',x.islower())
print('É capitalizada.',x.istitle())
